export type LaneFilter = "TOP" | "JUNGLE" | "MID" | "ADC" | "SUP";

/**
 * Main-role mapping only (off-meta lanes excluded).
 * Internal lane key uses "JUNGLE" (UI label can render as JGL).
 */
export const CHAMPION_ROLES: Record<string, LaneFilter[]> = {
  Aatrox: ["TOP"],
  Ahri: ["MID"],
  Akali: ["MID", "TOP"],
  Akshan: ["MID", "TOP"],
  Alistar: ["SUP"],
  Ambessa: ["TOP"],
  Amumu: ["JUNGLE", "SUP"],
  Anivia: ["MID"],
  Annie: ["MID", "SUP"],
  Aphelios: ["ADC"],
  Ashe: ["ADC", "SUP"],
  AurelionSol: ["MID"],
  Aurora: ["MID", "TOP"],
  Azir: ["MID"],
  Bard: ["SUP"],
  Belveth: ["JUNGLE"],
  Blitzcrank: ["SUP"],
  Brand: ["SUP", "MID"],
  Braum: ["SUP"],
  Briar: ["JUNGLE"],
  Caitlyn: ["ADC"],
  Camille: ["TOP"],
  Cassiopeia: ["MID"],
  Chogath: ["TOP", "MID"],
  Corki: ["MID", "ADC"],
  Darius: ["TOP"],
  Diana: ["JUNGLE", "MID"],
  DrMundo: ["TOP"],
  Draven: ["ADC"],
  Ekko: ["JUNGLE", "MID"],
  Elise: ["JUNGLE"],
  Evelynn: ["JUNGLE"],
  Ezreal: ["ADC"],
  Fiddlesticks: ["JUNGLE", "SUP"],
  Fiora: ["TOP"],
  Fizz: ["MID"],
  Galio: ["MID", "SUP"],
  Gangplank: ["TOP"],
  Garen: ["TOP"],
  Gnar: ["TOP"],
  Gragas: ["TOP", "JUNGLE"],
  Graves: ["JUNGLE"],
  Gwen: ["TOP", "JUNGLE"],
  Hecarim: ["JUNGLE"],
  Heimerdinger: ["MID", "SUP"],
  Hwei: ["MID"],
  Illaoi: ["TOP"],
  Irelia: ["TOP", "MID"],
  Ivern: ["JUNGLE"],
  Janna: ["SUP"],
  JarvanIV: ["JUNGLE"],
  Jax: ["TOP", "JUNGLE"],
  Jayce: ["TOP", "MID"],
  Jhin: ["ADC"],
  Jinx: ["ADC"],
  KSante: ["TOP"],
  Kaisa: ["ADC"],
  Kalista: ["ADC"],
  Karma: ["SUP", "MID"],
  Karthus: ["JUNGLE", "MID"],
  Kassadin: ["MID"],
  Katarina: ["MID"],
  Kayle: ["TOP"],
  Kayn: ["JUNGLE"],
  Kennen: ["TOP"],
  Khazix: ["JUNGLE"],
  Kindred: ["JUNGLE"],
  Kled: ["TOP"],
  KogMaw: ["ADC"],
  Leblanc: ["MID"],
  LeeSin: ["JUNGLE"],
  Leona: ["SUP"],
  Lillia: ["JUNGLE"],
  Lissandra: ["MID"],
  Lucian: ["ADC", "MID"],
  Lulu: ["SUP"],
  Lux: ["SUP", "MID"],
  Malphite: ["TOP"],
  Malzahar: ["MID"],
  Maokai: ["JUNGLE", "SUP", "TOP"],
  MasterYi: ["JUNGLE"],
  Mel: ["MID"],
  Milio: ["SUP"],
  MissFortune: ["ADC"],
  MonkeyKing: ["JUNGLE", "TOP"],
  Mordekaiser: ["TOP"],
  Morgana: ["SUP", "MID"],
  Naafiri: ["MID", "JUNGLE"],
  Nami: ["SUP"],
  Nasus: ["TOP"],
  Nautilus: ["SUP"],
  Neeko: ["MID", "SUP"],
  Nidalee: ["JUNGLE"],
  Nilah: ["ADC"],
  Nocturne: ["JUNGLE"],
  Nunu: ["JUNGLE"],
  Olaf: ["TOP", "JUNGLE"],
  Orianna: ["MID"],
  Ornn: ["TOP"],
  Pantheon: ["TOP", "MID", "SUP"],
  Poppy: ["JUNGLE", "TOP"],
  Pyke: ["SUP"],
  Qiyana: ["MID", "JUNGLE"],
  Quinn: ["TOP"],
  Rakan: ["SUP"],
  Rammus: ["JUNGLE"],
  RekSai: ["JUNGLE"],
  Rell: ["SUP", "JUNGLE"],
  Renata: ["SUP"],
  Renekton: ["TOP"],
  Rengar: ["JUNGLE", "TOP"],
  Riven: ["TOP"],
  Rumble: ["TOP", "JUNGLE"],
  Ryze: ["MID"],
  Samira: ["ADC"],
  Sejuani: ["JUNGLE"],
  Senna: ["ADC", "SUP"],
  Seraphine: ["SUP"],
  Sett: ["TOP"],
  Shaco: ["JUNGLE", "SUP"],
  Shen: ["TOP"],
  Shyvana: ["JUNGLE", "TOP"],
  Singed: ["TOP"],
  Sion: ["TOP"],
  Sivir: ["ADC"],
  Skarner: ["JUNGLE", "TOP"],
  Smolder: ["ADC"],
  Sona: ["SUP"],
  Soraka: ["SUP"],
  Swain: ["MID", "SUP"],
  Sylas: ["MID", "JUNGLE"],
  Syndra: ["MID"],
  TahmKench: ["SUP", "TOP"],
  Taliyah: ["JUNGLE", "MID"],
  Talon: ["MID", "JUNGLE"],
  Taric: ["SUP"],
  Teemo: ["TOP"],
  Thresh: ["SUP"],
  Tristana: ["ADC", "MID"],
  Trundle: ["JUNGLE", "TOP"],
  Tryndamere: ["TOP", "MID"],
  TwistedFate: ["MID"],
  Twitch: ["ADC"],
  Udyr: ["JUNGLE", "TOP"],
  Urgot: ["TOP"],
  Varus: ["ADC"],
  Vayne: ["ADC"],
  Veigar: ["MID", "SUP"],
  Velkoz: ["MID", "SUP"],
  Vex: ["MID"],
  Vi: ["JUNGLE"],
  Viego: ["JUNGLE"],
  Viktor: ["MID"],
  Vladimir: ["MID", "TOP"],
  Volibear: ["JUNGLE", "TOP"],
  Warwick: ["JUNGLE"],
  Xayah: ["ADC"],
  Xerath: ["MID", "SUP"],
  XinZhao: ["JUNGLE"],
  Yasuo: ["MID", "TOP"],
  Yone: ["MID", "TOP"],
  Yorick: ["TOP"],
  Yunara: ["MID"],
  Yuumi: ["SUP"],
  Zaahen: ["JUNGLE"],
  Zac: ["JUNGLE", "TOP"],
  Zed: ["MID", "JUNGLE"],
  Zeri: ["ADC"],
  Ziggs: ["MID", "ADC"],
  Zilean: ["SUP", "MID"],
  Zoe: ["MID"],
  Zyra: ["SUP", "MID"],
};

export function getChampionMainRoles(championId: string): LaneFilter[] {
  return CHAMPION_ROLES[championId] ?? [];
}

